
# config with settings server

# ------------------------------------------ #

# database host
host: "localhost"

# database name
dbname: "news_server"

# limit for query
limit: 20

# defult sort for news query 
defSortNews: "news_id"

# defult sort for news query 
defSortUser: "user_id"

# defult sort for news query 
defSortCat: "cat_id"

# defult sort for news query 
defSortImg: "img_id"

# log level: Debug | Info | Warn
loglevel: "Debug"

# tables in the database
tables:
  tableUser: "tableUser"
  tableCat: "tableCat"
  tableImG: "tableImG"
  tableNewsImG: "tableNewsImG"
  tableNewsRow: "tableNewsRow"

# ------------------------------------------ #
